### ISSUE TITLE
Provide an option which can turn off the Auto-update Check function

### ISSUE THREAD

**Issue by liwanglin12** [Vlvxingze/VLagger#11]
/blob/master/src/com/mcml/space/function/AutoUpdateCheck.java
A force notice after connection to server is ***objectionable***

**Comment by IzzelAliz** [comment]
Right, will add this in next release.

**Comment by liwanglin12** [comment]
（Actully you should close this issue after you completed this function, not before...）

**Comment by IzzelAliz** [comment]
已经好了，自己在 Circle CI 找。
实际上我们没有义务为你关闭这个功能。
如果想说英文，就不要用中文的括号

**Comment by liwanglin12** [comment]
Use English in international community such as Github is just to facilitate the other people.
This is a suggestion, not an order. If you don't want to close this function, you can tell me in the comment.

One more, http://bgm.mcml.space/VLagger/networker.yml is not accessible now. Error code: 404.
May you need to check this?

**Comment by SotrForgotten** [comment]
@Vlvxingze (You should contact the project owner

**Comment by IzzelAliz** [comment]
Unfortunately, I am not the administrator of this site。

**Comment by Vlvxingze** [comment]
Yes, in some countries, plugins cannot access those updates because of firewalls
In the plug-in, the automatic update switch is actually provided, located in PluginMainConfig.yml.
If your country or your firewall blocks my plug-in request (or a plug-in like YUM), you can turn this off.
If your plug-in does not have this configuration option, check your plug-in version and download the latest version

**Comment by IzzelAliz** [comment]
@Vlvxingze actually if you open that link you will find that you cannot access, too.

**Comment by Vlvxingze** [comment]
Uh! My mistake! I forgot to put in the update check file!

**Comment by liwanglin12** [comment]
@Vlvxingze I know you provide a setting to close auto-update, but when you close it, you will receive a notification when you log in to the server. So this is what I want to close.

**Comment by liwanglin12** [comment]
Now that you have used CI, you can try to use CI to automatically update version information

**Comment by Vlvxingze** [comment]
This notification will only appear in the OP tooltip, so don't worry

**Comment by Vlvxingze** [comment]
问题已经解决：
修复了自动更新网站
