### ISSUE TITLE
重新载入报错。

### ISSUE THREAD

**Issue by juzhijian** [Vlvxingze/VLagger#13]
![qq 20170728180801](https://user-images.githubusercontent.com/14793250/28712974-d053dca6-73bf-11e7-8928-d68a23abd919.png)
重新载入报错。

**Comment by Vlvxingze** [comment]
PluginMainConfig格式不正确
执行以下操作：
1.删除PluginMainConfig，并输入/vlg reload要求其重载一份
2.确保编码正确，重新编辑你的配置文件

如果仍然有问题随时问题

**Comment by juzhijian** [comment]
当时我确实删除了。重新载入之后还是那样。还有PluginPrefix改了名字之后发现没什么效果。

**Comment by Vlvxingze** [comment]
下载最新版本测试
