### ISSUE TITLE
显示错了。其实也不是什么大问题

### ISSUE THREAD

**Issue by juzhijian** [Vlvxingze/VLagger#14]
![qq 20170729165833](https://user-images.githubusercontent.com/14793250/28743702-1d070bcc-7483-11e7-9089-e8e5bb35a1ae.png)

**Comment by SotrForgotten** [comment]
你是想说信息前缀的彩色字符问题还是Spigot服务端的问题

**Comment by SotrForgotten** [comment]
如果是后者请提供当前的服务端信息

**Comment by juzhijian** [comment]
颜色。

**Comment by juzhijian** [comment]
- -到底Thermos应该怎么设置无人重启啊。

**Comment by IzzelAliz** [comment]
无人重启需要在你的开服脚本里加上循环，然后找个无人重启插件
