### ISSUE TITLE
玩家反馈不能自动复活

### ISSUE THREAD

**Issue by IzzelAliz** [Vlvxingze/VLagger#16]
端 Spigot 1.11.2
个别玩家反馈自动复活失效，已经显示了 Title，但是不复活
修不了就算了，我怀疑是客户端问题

**Comment by Vlvxingze** [comment]
我也很奇怪，代码没有任何问题
有些服务器就正常，有些就很奇怪。。
不过这个功能不重要，可以忽略

**Comment by Vlvxingze** [comment]
对了，还有问题可以随时留言=-=
