### ISSUE TITLE
README 和项目描述中的一些问题

### ISSUE THREAD

**Issue by andylizi** [Vlvxingze/VLagger#19]
> VLagger 是一款 MineCraft Bukkit 服务端插件，主要作用为优化运行、修复漏洞、限制动作的一款插件。本插件遵守V3协议开源。 此处为源码构建区，您可以到这里下载 Release 正式版本

> VLagger 是一款 MineCraft Bukkit 服务端插件，主要作用为优化运行、修复漏洞、限制动作的一款插件。本插件遵守GPL_v3协议开源。

-----

1. Minecraft 的名字是 `Minecraft`  不是 `MineCraft`。这还不如叫 `我的世界` 呢，至少 `我的世界` 是官方承认的译名。

2. 把那个协议称为 `GPLv3`、`GPL v3`、`GPL3`、`GPL-3`、`GPL 3`、`GPL 3.0`、`GPL-3.0` 等等都没问题都 ok，但 `V3协议` 和 `GPL_v3` 是什么东西？

3. 中文维基百科对于 `构建系统` [一词的定义](https://zh.wikipedia.org/wiki/%E6%9E%84%E5%BB%BA%E7%B3%BB%E7%BB%9F)为：

> 在软件开发中，构建系统(build system)是用来从源代码生成用户可以使用的目标的自动化工具。目标可以包括库、可执行文件、或者生成的脚本等等。

由此得出：
> 构建(build)是指从源代码生成用户可以使用的目标的过程。目标可以包括库、可执行文件、或者生成的脚本等等。

那么 `源码构建区` 是什么？

4. 
> 主要作用为优化运行、修复漏洞、限制动作的一款插件。

小学作文中是不应该出现这种极其明显的语病的。

**Comment by Vlvxingze** [comment]
我知道了，于下次推送修改
但是直接说别人 “小学作文”，我不喜欢这个词汇

**Comment by andylizi** [comment]
您误会了。我不是说您的README之类的是小学作文。我是指这个错误是都不到小学作文级别的。

**Comment by IzzelAliz** [comment]
这波可以
我邮箱都收到邮件了

**Comment by Vlvxingze** [comment]
好吧，我会推的更新
