### ISSUE TITLE
用户建议：红石检测算法修改

### ISSUE THREAD

**Issue by Vlvxingze** [Vlvxingze/VLagger#5]
建议：检测高频红石算法有些缺陷，中继器经常会被误清理。

任务：重写算法
或者使用 PandaWire 的算法来解决这个问题

鸣谢：建议来自——1349905649 （备忘）

**Comment by SotrForgotten** [comment]
@Vlvxingze PandaWire 的算法不能解决此问题

**Comment by Vlvxingze** [comment]
噢，好吧，谢谢提示= =
我去想办法
